name: Build and Push to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: offchain-labs/prysm-docs
  ECR_REGISTRY: 352956043285.dkr.ecr.us-west-2.amazonaws.com

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for AWS OIDC auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # AWS IAM role with ECR push permissions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        run: |
          # Try to get the most recent tag
          GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [[ -n "$GIT_TAG" ]]; then
            # Remove 'v' prefix if present
            VERSION=${GIT_TAG#v}
          else
            # Development version with commit sha
            VERSION="dev.$(git rev-parse --short HEAD)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.get_version.outputs.version }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      # Commented out: Helm chart update
      # - name: Checkout helm charts repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: your-org/helm-charts
      #     path: helm-charts
      #     token: ${{ secrets.PAT_TOKEN }}
      
      # - name: Update Helm chart values
      #   run: |
      #     cd helm-charts/charts/prysm-documentation
      #     # Update image.tag in values.yaml
      #     sed -i "s/tag:.*/tag: ${{ steps.get_version.outputs.version }}/" values.yaml
      
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.PAT_TOKEN }}
      #     commit-message: "chore: update prysm-documentation image to ${{ steps.get_version.outputs.version }}"
      #     title: "chore: update prysm-documentation image to ${{ steps.get_version.outputs.version }}"
      #     body: "Updates the prysm-documentation image tag to ${{ steps.get_version.outputs.version }}"
      #     branch: "update-prysm-docs-image"
      #     base: main
