name: not-implemented

on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  not-implemented:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Check label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "not implemented"
